import astropy.units as u

kepler_unit_map = {
    "ra": u.degree,
    "dec": u.degree,
    "jmag": u.mag,
    "hmag": u.mag,
    "kmag": u.mag,
    "teff": u.Kelvin,
    "teff_err1": u.Kelvin,
    "teff_err2": u.Kelvin,
	#"logg": u.Dex(u.g / u.cm**2),
	#"logg_err1": u.Dex(u.g / u.cm**2),
	#"logg_err2": u.Dex(u.g / u.cm**2),
	#"feh": u.Dex,	
	#"feh_err1": u.Dex,	
	#"feh_err2": u.Dex,	
	"mass": u.M_sun,
	"mass_err1": u.M_sun,
	"mass_err2": u.M_sun,
	"radius": u.R_sun,
	"radius_err1": u.R_sun,
	"radius_err2": u.R_sun,
	"dens": u.g / u.cm**3,
	"dens_err1": u.g / u.cm**3,
	"dens_err2": u.g / u.cm**3,
    "k2_teff": u.Kelvin,
    "k2_tefferr1": u.Kelvin,
    "k2_tefferr2": u.Kelvin,
	#"k2_logg": u.Dex(u.g / u.cm**2),
	#"k2_loggerr1": u.Dex(u.g / u.cm**2),
	#"k2_loggerr2": u.Dex(u.g / u.cm**2),
	#"k2_metfe": u.Dex,	
	#"k2_metfeerr1": u.Dex,	
	#"k2_metfeerr2": u.Dex,	
	"k2_mass": u.M_sun,
	"k2_masserr1": u.M_sun,
	"k2_masserr2": u.M_sun,
	"k2_rad": u.R_sun,
	"k2_raderr1": u.R_sun,
	"k2_raderr2": u.R_sun,
}


gaia_unit_map = {
    'angDist': u.arcsec,
    'ra': u.degree,
    'dec': u.degree,
    'ra_ep2000': u.degree,
    'dec_ep2000': u.degree,
    'parallax': u.milliarcsecond,
    'pmra': u.milliarcsecond / u.year,
    'pmdec': u.milliarcsecond / u.year,
    'radial_velocity': u.km / u.s,
    'ra_error': u.milliarcsecond,
    'dec_error': u.milliarcsecond,
    'parallax_error': u.milliarcsecond,
    'pmra_error': u.milliarcsecond / u.year,
    'pmdec_error': u.milliarcsecond / u.year,
    'radial_velocity_error': u.km / u.s,
    'astrometric_excess_noise': u.mas,
    'astrometric_weight_al': 1/u.mas**2,
    'astrometric_pseudo_colour': 1/u.micrometer,
    'astrometric_pseudo_colour_error': 1/u.micrometer,
    'astrometric_sigma5d_max': u.mas,
    'phot_g_mean_flux': u.photon/u.s,
    'phot_g_mean_flux_error': u.photon/u.s,
    'phot_g_mean_mag': u.mag,
    'phot_bp_mean_flux': u.photon/u.s,
    'phot_bp_mean_flux_error': u.photon/u.s,
    'phot_bp_mean_mag': u.mag,
    'phot_rp_mean_flux': u.photon/u.s,
    'phot_rp_mean_flux_error': u.photon/u.s,
    'phot_rp_mean_mag': u.mag,
    'bp_rp': u.mag,
    'bp_g': u.mag,
    'g_rp': u.mag,
    'rv_template_teff': u.K,
    'l': u.degree,
    'b': u.degree,
    'ecl_lon': u.degree,
    'ecl_lat': u.degree,
    'teff_val': u.K,
    'teff_percentile_lower': u.K,
    'teff_percentile_upper': u.K,
    'a_g_val': u.mag,
    'a_g_percentile_lower': u.mag,
    'a_g_percentile_upper': u.mag,
    'e_bp_min_rp_val': u.mag,
    'e_bp_min_rp_percentile_lower': u.mag,
    'e_bp_min_rp_percentile_upper': u.mag,
    'radius_val': u.Rsun,
    'radius_percentile_lower': u.Rsun,
    'radius_percentile_upper': u.Rsun,
    'lum_val': u.Lsun,
    'lum_percentile_lower': u.Lsun,
    'lum_percentile_upper': u.Lsun,
}